Algoritmo "Combinações"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : O programa que faz uma contagem aninhada
// Autor(a)    : Nelliel Bellamy
// Data atual  : 13/05/2025
Var
contador,contador2:inteiro
Inicio
para contador <- 1 ate 3 faca
     para contador2 <- 1 ate 3 faca
          Escreval(contador,contador2)
     fimpara
fimpara
Fimalgoritmo