Algoritmo "Soma entre 2 números"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Ele faz a soma entre 2 números
// Autor(a)    : Nelliel Bellamy
// Data atual  : 01/05/2025
Var
numero1,numero2,soma:inteiro

Inicio
Escreva("Digite o 1° número: ")
leia(numero1)
Escreva("Digite o 2° número: ")
leia(numero2)
soma <- numero1+numero2
Escreva("A soma entre ",numero1," e ",numero2," é igual a: ",soma,".")

Fimalgoritmo