Algoritmo "Par ou ímpar"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : O programa analisa se o número é par ou ímpar
// Autor(a)    : Nelliel Bellamy
// Data atual  : 05/05/2025
Var
numero:inteiro

Inicio
Escreva("Digite um número qualquer: ")
Leia(numero)
se (numero %2 = 0) entao
   Escreval("O número ",numero," é par!")
senao
     Escreval("O número",numero," é ímpar!")
fimse
Fimalgoritmo