Algoritmo "20. Verificador de Número Par ou Ímpar"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Programa que lê um número inteiro e informa se ele é par ou ímpar.
// Autor(a)    : Nelliel Bellamy
// Data atual  : 18/07/2025
Var
numero:inteiro
Inicio
Escreva("Digite um número qualquer: ")
Leia(numero)
Se (numero % 2 = 0)entao
   Escreval("O número",numero," é PAR!")
Senao
   Escreval("O número",numero," é ÍMPAR!")
fimse
Fimalgoritmo