Algoritmo "2. Mensagem de Boas-Vindas Personalizada"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Programa que lê o nome do usuário e exibe uma saudação personalizada na tela.
// Autor(a)    : Nelliel Bellamy
// Data atual  : 15/07/2025
Var
nomeUsuario:caractere
Inicio
Escreva("Digite o seu nome: ")
Leia(nomeUsuario)
Escreval("Seja Bem-vindo(a), ",nomeUsuario,"! É um prazer te conhecer!")
Fimalgoritmo