Algoritmo "6. Antecessor e Sucessor de um Número"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Programa que lê um número inteiro e exibe seu antecessor e sucessor.
// Autor(a)    : Nelliel Bellamy
// Data atual  : 15/07/2025
Var
numero:inteiro
Inicio
Escreva("Digite um número: ")
Leia(numero)
Escreval("O sucessor do número ",numero," é igual a ",numero+1," e o seu antecessor é igual a ",numero-1,".")
Fimalgoritmo